name: Update Build Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Build
        run: npm run build

      - name: Create parallel branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b build
          git add dist/
          git commit -m "build"
          git push origin build
